import { CA_COUNTIES } from "./caCounties.js";

/** State and city vital-records desks.
 * Mail addresses follow the 2026 Where-to-Write compilation used by county recorders.
 * A website link is not the same as a finished online order. Every desk below can be reached by mail.
 */

function office({ code, name, office, mail, phone, url, payableTo, paymentNote, inPerson, birth, death, marriage, divorce, counties, dmv }) {
  const stateBirth = {
    holder: "state",
    portal: "partial",
    since: birth?.since || "",
    localNote: birth?.localNote || "",
  };
  return {
    code,
    name,
    vital: {
      office,
      mail,
      phone,
      url,
      payableTo: payableTo || office.split("\n")[0],
      paymentNote: paymentNote || "Send a check or money order for the current certified-copy fee. Do not send cash. If the fee changed, ask the office to bill the difference or return the payment with the current fee.",
      inPerson: inPerson || "",
    },
    records: {
      birth: stateBirth,
      death: {
        holder: death?.holder || "state",
        portal: death?.portal || "partial",
        since: death?.since || birth?.since || "",
        localNote: death?.localNote || birth?.localNote || "",
      },
      marriage: {
        holder: marriage?.holder || "both",
        portal: marriage?.portal || (marriage?.holder === "county" ? "none" : "partial"),
        since: marriage?.since || "",
        localNote: marriage?.localNote || "If the state index does not have the license, the county or town clerk where it was issued still has it.",
      },
      divorce: {
        holder: divorce?.holder || "court",
        portal: divorce?.portal || "none",
        since: divorce?.since || "",
        localNote: divorce?.localNote || "A divorce decree is a court record. Mail the clerk of the court that granted it. The state vital-records office can often tell you which court, even when it cannot sell the decree.",
      },
      adoption: {
        holder: "state",
        portal: "none",
        since: birth?.since || "",
        localNote: "Order the birth certificate in the current legal name by mail. If a pre-adoption record is sealed, the office must say so in writing and point to the court or adult-adoptee process. This service does not unseal a court record.",
      },
      driver: {
        holder: "dmv",
        portal: dmv?.portal || "partial",
        since: "",
        localNote: dmv?.localNote || "You can request your own driver record. The state still checks identity under the Driver's Privacy Protection Act.",
      },
    },
    counties: counties || [],
    dmv: {
      office: dmv?.office || `${name} motor vehicle records unit`,
      mail: dmv?.mail || "",
      phone: dmv?.phone || "",
      url: dmv?.url || "https://www.usa.gov/motor-vehicle-services",
      payableTo: dmv?.payableTo || `${name} Department of Motor Vehicles`,
    },
  };
}

export const JURISDICTIONS = [
  office({
    code: "AL",
    name: "Alabama",
    office: "Alabama Department of Public Health\nCenter for Health Statistics",
    mail: "Alabama Department of Public Health\nCenter for Health Statistics\nP.O. Box 5625\nMontgomery, AL 36103-5625",
    phone: "(334) 206-5426",
    url: "https://www.alabamapublichealth.gov/vitalrecords/",
    paymentNote: "No personal checks. Business checks and money orders are accepted. Confirm the current fee before you mail payment.",
    birth: { since: "January 1908", localNote: "Statewide birth and death records begin January 1908. Earlier events are with the county probate office." },
    marriage: { holder: "state", since: "August 1936", localNote: "State marriage records begin August 1936. Earlier licenses are at the probate court in the county where the license was issued." },
  }),
  office({
    code: "AK",
    name: "Alaska",
    office: "State of Alaska\nHealth Analytics and Vital Records",
    mail: "State of Alaska\nHealth Analytics and Vital Records\nP.O. Box 110675\nJuneau, AK 99811-0675",
    phone: "(907) 465-3391",
    url: "https://health.alaska.gov/dph/VitalStats/Pages/fees.aspx",
    birth: { since: "1890" },
    marriage: { holder: "state", since: "1913" },
  }),
  office({
    code: "AZ",
    name: "Arizona",
    office: "Arizona Office of Vital Records",
    mail: "Arizona Office of Vital Records\nP.O. Box 6018\nPhoenix, AZ 85030",
    phone: "(602) 364-1300",
    url: "https://www.azdhs.gov/licensing/vital-records/index.php",
    birth: { since: "July 1909", localNote: "The state office has records since July 1909 and some earlier county abstracts. Marriage and divorce records are not sold by this office." },
    marriage: { holder: "county", portal: "none", since: "", localNote: "Mail the Clerk of the Superior Court in the county where the license was issued." },
  }),
  office({
    code: "AR",
    name: "Arkansas",
    office: "Arkansas Department of Health\nVital Records",
    mail: "Arkansas Department of Health\nVital Records, Slot 44\n4815 West Markham Street\nLittle Rock, AR 72205",
    phone: "(501) 661-2336",
    url: "https://www.healthy.arkansas.gov/programs-services/topics/vital-records",
    inPerson: "4815 West Markham Street, Little Rock, AR 72205",
    birth: { since: "February 1914", localNote: "Statewide filing begins February 1914. Some Little Rock and Fort Smith records exist from 1881." },
    marriage: { holder: "both", since: "1917", localNote: "The county clerk or circuit clerk where the license was recorded can also issue a copy." },
  }),
  office({
    code: "CA",
    name: "California",
    office: "California Department of Public Health\nOffice of Vital Records",
    mail: "California Department of Public Health\nOffice of Vital Records\nMS 5103\nP.O. Box 997410\nSacramento, CA 95899-7410",
    phone: "(916) 445-2684",
    url: "https://www.cdph.ca.gov/Programs/CHSI/Pages/Vital-Records.aspx",
    birth: { since: "July 1905", localNote: "For events before July 1905, mail the county recorder where the event happened. County recorders can also issue many later certificates, which helps when the state portal rejects a former name." },
    marriage: { holder: "both", since: "July 1905", localNote: "County recorders issue marriage certificates. Use the county desk when the state site has no working order path." },
    counties: CA_COUNTIES,
  }),
  office({
    code: "CO",
    name: "Colorado",
    office: "Colorado Department of Public Health and Environment\nVital Records",
    mail: "Vital Records\n4300 Cherry Creek Drive South\nDenver, CO 80246-1530",
    phone: "(303) 692-2200",
    url: "https://cdphe.colorado.gov/vitalrecords",
    inPerson: "4300 Cherry Creek Drive South, Denver, CO 80246-1530",
    birth: { since: "1910", localNote: "Death records begin in 1900. Birth records begin in 1910, with some earlier county records. Marriage licenses are issued by the county clerk." },
    death: { since: "1900" },
    marriage: { holder: "county", portal: "none", localNote: "Mail the county clerk in the county where the license was issued." },
  }),
  office({
    code: "CT",
    name: "Connecticut",
    office: "Connecticut Department of Public Health\nVital Records Section",
    mail: "State of Connecticut\nDepartment of Public Health\nVital Records Section\nMS# IIVRS, P.O. Box 340308\nHartford, CT 06134-0308",
    phone: "(860) 509-7700",
    url: "https://portal.ct.gov/dph/vital-records/vital-records",
    birth: { since: "July 1897", localNote: "For events before July 1897, write the registrar of vital statistics in the town where the event happened." },
    marriage: { holder: "state", since: "July 1897", localNote: "Town registrars also keep marriage records and can mail a copy when the state portal is not an option." },
  }),
  office({
    code: "DE",
    name: "Delaware",
    office: "Delaware Office of Vital Statistics",
    mail: "Jesse Cooper Building\nOffice of Vital Statistics\n417 Federal Street\nDover, DE 19901",
    phone: "(302) 744-4549",
    url: "https://www.dhss.delaware.gov/dhss/dph/ss/vitalstats.html",
    inPerson: "417 Federal Street, Dover, DE 19901",
    birth: { since: "1920", localNote: "Birth records at this office begin in 1920. Death and marriage records begin in 1930. Older records went to the Delaware Public Archives in Dover." },
    marriage: { holder: "state", since: "1930" },
  }),
  office({
    code: "DC",
    name: "District of Columbia",
    office: "DC Health\nVital Records Division",
    mail: "Vital Records Division\n899 N. Capitol Street N.E., First Floor\nWashington, DC 20002",
    phone: "(202) 442-5955",
    url: "https://dchealth.dc.gov/service/vital-records",
    inPerson: "899 N. Capitol Street N.E., First Floor, Washington, DC 20002",
    birth: { since: "August 1874" },
    marriage: {
      holder: "court",
      portal: "none",
      localNote: "Marriage licenses are at the DC Superior Court Marriage Bureau, not the health department.",
    },
  }),
  office({
    code: "FL",
    name: "Florida",
    office: "Florida Department of Health\nBureau of Vital Statistics",
    mail: "Department of Health\nBureau of Vital Statistics\nAttn: Vital Records Section\nP.O. Box 210\nJacksonville, FL 32231-0042",
    phone: "(904) 359-6900",
    url: "https://www.floridahealth.gov/certificates/certificates/",
    birth: { since: "Most records from January 1917; some births from April 1865", localNote: "If the exact year is unknown, say so in the letter and ask for a search. Marriage records before June 6, 1927 are at the clerk of the circuit court." },
    marriage: { holder: "both", since: "June 6, 1927", localNote: "Licenses before June 6, 1927: mail the Clerk of the Circuit Court in the county where the license was issued." },
    divorce: { holder: "both", localNote: "The state office has many divorce records. The clerk of the circuit court in the county of the decree can also mail a copy." },
  }),
  office({
    code: "GA",
    name: "Georgia",
    office: "Georgia State Vital Records Office",
    mail: "State Vital Records Office\n1680 Phoenix Boulevard, Suite 100\nAtlanta, GA 30349",
    phone: "(404) 657-2700",
    url: "https://dph.georgia.gov/ways-request-vital-record",
    inPerson: "1680 Phoenix Boulevard, Suite 100, Atlanta, GA 30349",
    birth: { since: "January 1919", localNote: "Earlier Atlanta or Savannah records may be with the county health department or probate court." },
    marriage: { holder: "both", since: "June 9, 1952", localNote: "Licenses before June 9, 1952 are at the probate court in the county where the license was issued." },
  }),
  office({
    code: "HI",
    name: "Hawaii",
    office: "Hawaii Department of Health\nVital Statistics Section",
    mail: "State Department of Health\nOffice of Health Status Monitoring\nVital Statistics Section\nP.O. Box 3378\nHonolulu, HI 96801",
    phone: "(808) 586-4539",
    url: "https://health.hawaii.gov/vitalrecords/",
    birth: { since: "1853" },
    marriage: { holder: "state", since: "1853" },
    divorce: { holder: "both", since: "July 1951 to December 2002 at the health department", localNote: "Divorces outside July 1951–December 2002 are at the court where the divorce was granted." },
  }),
  office({
    code: "ID",
    name: "Idaho",
    office: "Idaho Vital Statistics",
    mail: "Idaho Vital Statistics\nP.O. Box 83720\nBoise, ID 83720-0036",
    phone: "(208) 334-5980",
    url: "https://healthandwelfare.idaho.gov/services-programs/birth-marriage-death-records",
    birth: { since: "1911", localNote: "For 1907–1911, mail the county recorder where the event happened." },
    marriage: { holder: "both", since: "May 1947", localNote: "Earlier marriage licenses are at the county recorder where the license was issued." },
  }),
  office({
    code: "IL",
    name: "Illinois",
    office: "Illinois Department of Public Health\nDivision of Vital Records",
    mail: "Illinois Department of Public Health\nDivision of Vital Records\n925 E. Ridgely Avenue\nSpringfield, IL 62702-2737",
    phone: "(217) 782-6554",
    url: "https://dph.illinois.gov/topics-services/birth-death-other-records",
    inPerson: "925 E. Ridgely Avenue, Springfield, IL 62702-2737",
    birth: { since: "January 1916", localNote: "County clerks can mail certified copies, including for years before 1916. Use the county clerk when the state site will not take the order." },
    marriage: { holder: "county", portal: "none", since: "State verifications only since January 1962", localNote: "A certified marriage copy comes from the county clerk where the license was issued. The state office gives verifications, not the certificate most agencies want." },
  }),
  office({
    code: "IN",
    name: "Indiana",
    office: "Indiana Department of Health\nVital Records",
    mail: "Indiana Department of Health\nVital Records\n2 North Meridian Street\nIndianapolis, IN 46206-7125",
    phone: "(317) 233-2700",
    url: "https://www.in.gov/health/vital-records/",
    inPerson: "2 North Meridian Street, Indianapolis, IN 46204",
    birth: { since: "October 1907", localNote: "Death records begin in 1900. Earlier events are with the local health officer." },
    death: { since: "1900" },
    marriage: { holder: "county", portal: "none", since: "State index since 1958", localNote: "Mail the Clerk of the Circuit Court or Clerk of the Superior Court in the county where the license was issued." },
  }),
  office({
    code: "IA",
    name: "Iowa",
    office: "Iowa Health and Human Services\nVital Records",
    mail: "Iowa HHS — Vital Records\n321 E. 12th Street\nDes Moines, IA 50319-0075",
    phone: "(515) 281-4944",
    url: "https://hhs.iowa.gov/health-prevention/vital-records",
    inPerson: "321 E. 12th Street, Des Moines, IA 50319",
    birth: { since: "July 1880", localNote: "Counties hold most records. Births from 1921–1941 are a known gap at some county offices, so mail the state office for those years." },
    marriage: { holder: "both", since: "July 1880" },
  }),
  office({
    code: "KS",
    name: "Kansas",
    office: "Kansas Office of Vital Statistics",
    mail: "Kansas Department of Health and Environment\nOffice of Vital Statistics\n1000 SW Jackson, Suite 120\nTopeka, KS 66612-2221",
    phone: "(785) 296-1400",
    url: "https://www.kdhe.ks.gov/1165/Office-of-Vital-Statistics",
    inPerson: "1000 SW Jackson, Suite 120, Topeka, KS 66612",
    birth: { since: "July 1911", localNote: "Earlier records are with the county where the event happened." },
    marriage: { holder: "state", since: "May 1913" },
  }),
  office({
    code: "KY",
    name: "Kentucky",
    office: "Kentucky Office of Vital Statistics",
    mail: "Commonwealth of Kentucky\nOffice of Vital Statistics\n275 East Main Street, 1E-A\nFrankfort, KY 40621",
    phone: "(502) 564-4212",
    url: "https://www.chfs.ky.gov/agencies/dph/dehp/vsb/Pages/default.aspx",
    inPerson: "275 East Main Street, Frankfort, KY 40621",
    birth: { since: "1911 statewide; some earlier records", localNote: "Marriage licenses are also at the county clerk. Mail the county clerk if you need the license the state index does not release as a certified copy." },
    marriage: { holder: "both", localNote: "County clerks issue marriage licenses. Mail that clerk when the state office cannot provide the certified copy you need." },
  }),
  office({
    code: "LA",
    name: "Louisiana",
    office: "Louisiana Bureau of Vital Records and Statistics",
    mail: "Bureau of Vital Records and Statistics\nP.O. Box 60630\nNew Orleans, LA 70160",
    phone: "(504) 593-5100",
    url: "https://ldh.la.gov/page/vital-records",
    birth: { since: "July 1914", localNote: "New Orleans birth records go back to 1790 and death records to 1803." },
    marriage: { holder: "county", portal: "none", since: "Orleans Parish at the state office", localNote: "Outside Orleans Parish, mail the Clerk of Court in the parish where the license was issued. For Orleans Parish, mail the state office in New Orleans." },
  }),
  office({
    code: "ME",
    name: "Maine",
    office: "Maine Division of Data, Research, and Vital Statistics",
    mail: "Division of Data, Research, and Vital Statistics\n220 Capitol Street\nAugusta, ME 04333-0011",
    phone: "(207) 287-1919",
    url: "https://www.maine.gov/dhhs/mecdc/public-health-systems/data-research/vital-records",
    inPerson: "220 Capitol Street, Augusta, ME 04333",
    birth: { since: "1892", localNote: "Earlier records are at the municipality where the event happened." },
    marriage: { holder: "both", localNote: "The town clerk where the license was issued can mail a copy. Use that path when the state order system will not accept a former name." },
  }),
  office({
    code: "MD",
    name: "Maryland",
    office: "Maryland Division of Vital Records",
    mail: "Division of Vital Records\n6764B Reisterstown Road\nBaltimore, MD 21215",
    phone: "(410) 764-3038",
    url: "https://health.maryland.gov/vsa/Pages/birth.aspx",
    inPerson: "6764B Reisterstown Road, Baltimore, MD 21215",
    birth: { since: "August 1898", localNote: "Baltimore City records begin in January 1875." },
    marriage: { holder: "both", since: "June 1951", localNote: "Also mail the Clerk of the Circuit Court in the county of the license, or the Court of Common Pleas for Baltimore City." },
  }),
  office({
    code: "MA",
    name: "Massachusetts",
    office: "Massachusetts Registry of Vital Records and Statistics",
    mail: "Registry of Vital Records\n150 Mount Vernon Street, 1st Floor\nDorchester, MA 02125-3105",
    phone: "(617) 740-2600",
    url: "https://www.mass.gov/how-to/order-a-birth-marriage-or-death-certificate",
    inPerson: "150 Mount Vernon Street, 1st Floor, Dorchester, MA 02125",
    birth: { since: "1906 at the Registry", localNote: "Records from 1841–1905: mail the Massachusetts Archives, 220 Morrissey Boulevard, Boston, MA 02125, or the city or town clerk. Town clerks can mail later records too." },
    marriage: { holder: "both", since: "1906 at the Registry", localNote: "The city or town clerk where the license was issued can mail a copy, including when the state site is down." },
  }),
  office({
    code: "MI",
    name: "Michigan",
    office: "Michigan Vital Records",
    mail: "Michigan Vital Records Request\nP.O. Box 30721\nLansing, MI 48909",
    phone: "(517) 335-8666",
    url: "https://www.michigan.gov/mdhhs/adult-child-serv/children-families/vital-records",
    birth: { since: "1867", localNote: "County clerks can mail copies of records since 1867. Detroit city records: births since 1893 and deaths since 1897 may also be requested from the city." },
    marriage: { holder: "county", portal: "none", since: "April 1867", localNote: "Mail the county clerk in the county where the license was issued." },
  }),
  office({
    code: "MN",
    name: "Minnesota",
    office: "Minnesota Department of Health\nOffice of Vital Records",
    mail: "Minnesota Department of Health\nOffice of Vital Records\nP.O. Box 64499\nSt. Paul, MN 55164-0499",
    phone: "(651) 201-5970",
    url: "https://www.health.state.mn.us/people/vitalrecords/index.html",
    birth: { since: "January 1908", localNote: "Earlier birth and death records are with the local registrar in the county of the event." },
    marriage: { holder: "county", portal: "none", localNote: "Mail the local registrar or court administrator in the county where the license was issued." },
  }),
  office({
    code: "MS",
    name: "Mississippi",
    office: "Mississippi Vital Records",
    mail: "Mississippi Vital Records\nP.O. Box 1700\nJackson, MS 39215-1700",
    phone: "(601) 206-8200",
    url: "https://msdh.ms.gov/msdhsite/index.cfm/31,0,75,html",
    birth: { since: "1912" },
    marriage: { holder: "county", portal: "none", since: "Certified copies from the circuit clerk", localNote: "The state office has statistical marriage records for parts of 1926–1938 and from 1942. A certified copy comes from the circuit clerk where the license was issued." },
  }),
  office({
    code: "MO",
    name: "Missouri",
    office: "Missouri Bureau of Vital Records",
    mail: "Missouri Department of Health and Senior Services\nBureau of Vital Records\n930 Wildwood Drive\nJefferson City, MO 65109",
    phone: "(573) 751-6387",
    url: "https://health.mo.gov/data/vitalrecords/",
    inPerson: "930 Wildwood Drive, Jefferson City, MO 65109",
    birth: { since: "January 1910", localNote: "St. Louis City, St. Louis County, and Kansas City events before 1910 are at those local health departments." },
    marriage: { holder: "county", portal: "none", localNote: "The state office has an index only. Mail the Recorder of Deeds in the county where the license was issued." },
  }),
  office({
    code: "MT",
    name: "Montana",
    office: "Montana Vital Records",
    mail: "Montana Vital Records\nP.O. Box 4210\nHelena, MT 59604",
    phone: "(406) 444-2685",
    url: "https://dphhs.mt.gov/vitalrecords",
    birth: { since: "late 1907" },
    marriage: { holder: "county", portal: "none", localNote: "Mail the Clerk of District Court in the county where the license was issued." },
  }),
  office({
    code: "NE",
    name: "Nebraska",
    office: "Nebraska Vital Records",
    mail: "Nebraska Vital Records\nP.O. Box 95065\nLincoln, NE 68509-5065",
    phone: "(402) 471-2871",
    url: "https://dhhs.ne.gov/Pages/Vital-Records.aspx",
    birth: { since: "late 1904", localNote: "For a birth before 1904, still mail this office and ask where the record is filed." },
    marriage: { holder: "state", since: "1909" },
  }),
  office({
    code: "NV",
    name: "Nevada",
    office: "Nevada Office of Vital Records and Statistics",
    mail: "Office of Vital Records and Statistics\nAttn: Customer Service\n4150 Technology Way, Suite 104\nCarson City, NV 89706",
    phone: "(775) 684-4242",
    url: "https://dpbh.nv.gov/Programs/VitalRecords/",
    inPerson: "4150 Technology Way, Suite 104, Carson City, NV 89706",
    birth: { since: "July 1911", localNote: "Earlier records are at the county recorder where the event happened." },
    marriage: { holder: "county", portal: "none", localNote: "Mail the county recorder where the license was issued. Call that county for the current fee." },
    divorce: { holder: "both", localNote: "Call (775) 684-4242 if you are not sure which court issued the decree, then mail that court clerk." },
    dmv: {
      office: "Nevada DMV Central Services Records Division",
      mail: "Central Services Records Division\n555 Wright Way\nCarson City, NV 89711-0250",
      phone: "(775) 684-4590",
      url: "https://dmv.nv.gov/records.htm",
      payableTo: "Nevada DMV",
      localNote: "Include a copy of your driver license. An affidavit, when the DMV requires one, must be notarized. E-notary is accepted in many cases.",
    },
  }),
  office({
    code: "NH",
    name: "New Hampshire",
    office: "New Hampshire Division of Vital Records Administration",
    mail: "Department of State\nDivision of Vital Records Administration\n9 Ratification Way\nConcord, NH 03301-2455",
    phone: "(603) 271-4650",
    url: "https://www.sos.nh.gov/vital-records",
    inPerson: "9 Ratification Way, Concord, NH 03301",
    birth: { since: "Some records from 1640", localNote: "City and town clerks can also mail copies. Use the clerk where the event happened if the state counter is not an option." },
    marriage: { holder: "both", since: "1640", localNote: "The town or city clerk where the license was issued can mail a copy." },
  }),
  office({
    code: "NJ",
    name: "New Jersey",
    office: "New Jersey Office of Vital Statistics",
    mail: "New Jersey Office of Vital Statistics\nP.O. Box 370\nTrenton, NJ 08625-0370",
    phone: "(609) 292-4087",
    url: "https://www.nj.gov/health/vital/",
    birth: { since: "June 1878", localNote: "Records from May 1848 to May 1878 are also requested from this office or the New Jersey State Archives. If the year is uncertain, ask for a year-by-year search and confirm the search fee." },
    marriage: { holder: "state", since: "June 1878" },
  }),
  office({
    code: "NM",
    name: "New Mexico",
    office: "New Mexico Bureau of Vital Records and Health Statistics",
    mail: "New Mexico Department of Health\nBureau of Vital Records and Health Statistics\nP.O. Box 26110\nSanta Fe, NM 87502",
    phone: "(505) 827-0121",
    url: "https://www.nmhealth.org/about/erd/bvrhs/",
    birth: { since: "1920, plus delayed records from 1880" },
    marriage: { holder: "county", portal: "none", localNote: "Mail the county clerk where the license was issued." },
  }),
  office({
    code: "NY",
    name: "New York",
    office: "New York State Department of Health\nVital Records Certification Unit",
    mail: "New York State Department of Health\nVital Records Certification Unit\nP.O. Box 2602\nAlbany, NY 12220-2602",
    phone: "(855) 322-1022",
    url: "https://www.health.ny.gov/vital_records/mailrequests.htm",
    paymentNote: "The published mail fee is $30 per copy for birth, death, marriage, and divorce. Make the check payable to the New York State Department of Health. Do not send cash. Confirm the fee on the state page before mailing. New York City events are a different office — choose New York City in this app.",
    payableTo: "New York State Department of Health",
    birth: { since: "1881", localNote: "This office does not have New York City birth or death certificates. Before 1914 in Albany, Buffalo, and Yonkers, or before 1880 in other cities, mail the local registrar. Choose New York City if the event was in the five boroughs." },
    marriage: { holder: "state", since: "1880–1907 and May 1915 to present", localNote: "Licenses from January 1908 through April 1915 are at the county clerk. New York City marriage licenses are at the city clerk in the borough, not this office." },
    divorce: { holder: "state", portal: "partial", since: "", localNote: "New York State mails divorce certificates from this same post office box. A full judgment may still be at the court." },
  }),
  office({
    code: "NYC",
    name: "New York City",
    office: "NYC Department of Health and Mental Hygiene\nOffice of Vital Records",
    mail: "NYC Department of Health and Mental Hygiene\nOffice of Vital Records\n125 Worth Street, CN 4, Room 119\nNew York, NY 10013-4090",
    phone: "(212) 639-9675",
    url: "https://www.nyc.gov/site/doh/services/birth-death-records-birth.page",
    inPerson: "125 Worth Street, New York, NY 10013",
    birth: { since: "Birth and death records for the five boroughs", localNote: "Do not mail Albany for a New York City birth or death. The city office is the right desk." },
    marriage: { holder: "court", portal: "none", localNote: "Marriage licenses are issued by the New York City Clerk in the borough where the license was filed, not by the health department. Mail the City Clerk's Office for that borough and ask for the marriage-record mailing address if you do not have it." },
  }),
  office({
    code: "NC",
    name: "North Carolina",
    office: "North Carolina Vital Records",
    mail: "North Carolina Vital Records\n1903 Mail Service Center\nRaleigh, NC 27699-1900",
    phone: "(919) 733-3000",
    url: "https://vitalrecords.nc.gov/",
    birth: { since: "October 1913", localNote: "Death records before 1930 were transferred to the State Archives, 215 North Blount Street, Raleigh, NC 27602." },
    death: { since: "1913; deaths before 1930 are at the State Archives", localNote: "For a death before 1930, mail the State Archives, 215 North Blount Street, Raleigh, NC 27602, and also say so in the letter to Vital Records." },
    marriage: { holder: "both", since: "January 1962", localNote: "Licenses before January 1962: mail the Register of Deeds in the county where the marriage was performed." },
  }),
  office({
    code: "ND",
    name: "North Dakota",
    office: "North Dakota Vital Records",
    mail: "North Dakota Department of Health and Human Services\nVital Records Unit\n600 E. Boulevard Avenue, Dept. 325\nBismarck, ND 58505-0200",
    phone: "(701) 328-2360",
    url: "https://www.hhs.nd.gov/vital",
    inPerson: "600 E. Boulevard Avenue, Bismarck, ND 58505",
    birth: { since: "Some records from July 1893; 1894–1920 are incomplete" },
    marriage: { holder: "both", since: "July 1925", localNote: "Licenses before July 1925 are at the clerk of court in the county where the license was issued." },
  }),
  office({
    code: "OH",
    name: "Ohio",
    office: "Ohio Department of Health\nBureau of Vital Statistics",
    mail: "Ohio Department of Health\nBureau of Vital Statistics\nP.O. Box 15098\nColumbus, OH 43215-0098",
    phone: "(614) 466-2531",
    url: "https://odh.ohio.gov/know-our-programs/vital-statistics/how-to-order-certificates",
    birth: { since: "December 20, 1908", localNote: "Earlier records are at the probate court in the county of the event." },
    marriage: { holder: "county", portal: "none", localNote: "Mail the probate court in the county where the license was issued." },
  }),
  office({
    code: "OK",
    name: "Oklahoma",
    office: "Oklahoma Vital Records Service",
    mail: "Vital Records Service\nOklahoma State Department of Health\nP.O. Box 248964\nOklahoma City, OK 73124-8964",
    phone: "(405) 426-8880",
    url: "https://oklahoma.gov/health/services/vital-records.html",
    paymentNote: "Enclose a stamped, self-addressed envelope with the request, plus a check or money order for the current fee. Do not send cash.",
    birth: { since: "October 1908" },
    marriage: { holder: "county", portal: "none", localNote: "Mail the court clerk in the county where the license was issued." },
  }),
  office({
    code: "OR",
    name: "Oregon",
    office: "Oregon Vital Records",
    mail: "Oregon Vital Records\nP.O. Box 14050\nPortland, OR 97293-0050",
    phone: "(971) 673-1222",
    url: "https://www.oregon.gov/oha/ph/birthdeathcertificates/pages/index.aspx",
    birth: { since: "July 1903" },
    marriage: { holder: "both", since: "January 1906", localNote: "Licenses before January 1906 are at the county clerk. County clerks can also mail later licenses." },
  }),
  office({
    code: "PA",
    name: "Pennsylvania",
    office: "Pennsylvania Division of Vital Records",
    mail: "Pennsylvania Department of Health\nDivision of Vital Records\nAttn: Birth Unit\nP.O. Box 1528\nNew Castle, PA 16103",
    phone: "(724) 656-3100",
    url: "https://www.pa.gov/agencies/health/programs/vital-records.html",
    birth: { since: "January 1906", localNote: "Earlier records: mail the Register of Wills / Orphans' Court in the county seat where the event happened." },
    marriage: { holder: "county", portal: "none", localNote: "Marriage and divorce records are at the courthouse in the county of the event, not at the Division of Vital Records." },
    divorce: { holder: "court", portal: "none", localNote: "Mail the prothonotary or clerk of the court in the county that granted the divorce." },
  }),
  office({
    code: "RI",
    name: "Rhode Island",
    office: "Rhode Island Department of Health\nVital Records",
    mail: "Rhode Island Department of Health\nVital Records\nSimpson Hall\n6 Harrington Road\nCranston, RI 02920",
    phone: "(401) 222-5960",
    url: "https://health.ri.gov/records/",
    inPerson: "6 Harrington Road, Cranston, RI 02920",
    birth: { since: "1853", localNote: "The city or town clerk where the event happened can also mail a copy. Use that clerk if the state office cannot find the name you use now." },
    marriage: { holder: "both", since: "January 1853", localNote: "Mail the city or town clerk where the marriage was performed if you need a local certified copy." },
  }),
  office({
    code: "SC",
    name: "South Carolina",
    office: "South Carolina Department of Public Health\nVital Records",
    mail: "S.C. Department of Public Health\nVital Records\nP.O. Box 2046\nWest Columbia, SC 29171",
    phone: "(803) 898-3300",
    url: "https://dph.sc.gov/public/vital-records",
    birth: { since: "January 1915" },
    marriage: { holder: "both", since: "July 1950", localNote: "Earlier marriage licenses are at the probate court in the county where the license was issued." },
  }),
  office({
    code: "SD",
    name: "South Dakota",
    office: "South Dakota Vital Records",
    mail: "South Dakota Vital Records\n221 W. Capitol Avenue\nPierre, SD 57501",
    phone: "(605) 773-4961",
    url: "https://doh.sd.gov/licensing-and-records/vital-records/",
    inPerson: "221 W. Capitol Avenue, Pierre, SD 57501",
    birth: { since: "July 1905" },
    marriage: { holder: "both", since: "July 1905", localNote: "The register of deeds or county office that issued the license can also mail a copy." },
  }),
  office({
    code: "TN",
    name: "Tennessee",
    office: "Tennessee Vital Records",
    mail: "Tennessee Vital Records\nAndrew Johnson Tower, 1st Floor\n710 James Robertson Parkway\nNashville, TN 37243",
    phone: "(615) 741-1763",
    url: "https://www.tn.gov/health/health-program-areas/vital-records.html",
    inPerson: "710 James Robertson Parkway, 1st Floor, Nashville, TN 37243",
    birth: { since: "January 1914 for births statewide" },
    marriage: { holder: "both", since: "July 1945", localNote: "The county clerk where the license was issued can mail a copy, including licenses before July 1945." },
    divorce: { holder: "both", localNote: "The state office has many divorce certificates. The court clerk in the county of the decree can mail the judgment." },
  }),
  office({
    code: "TX",
    name: "Texas",
    office: "Texas Vital Statistics",
    mail: "Texas Vital Statistics\nDepartment of State Health Services\nP.O. Box 12040\nAustin, TX 78711-2040",
    phone: "(888) 963-7111",
    url: "https://www.dshs.texas.gov/vital-statistics/mail-request",
    paymentNote: "Use P.O. Box 12040 for regular mail. Overnight mail for expedited service goes to Texas Vital Statistics, MC 2096, 1100 W. 49th Street, Austin, TX 78756. Confirm the fee before you mail a check.",
    birth: { since: "1903", localNote: "County clerks can mail many birth and death records. Use the county clerk when the state portal will not match a former name." },
    marriage: { holder: "both", since: "January 1966 at the state office", localNote: "Every county clerk can mail the marriage license recorded there, including licenses before 1966." },
    divorce: { holder: "both", since: "1968 for many state divorce records", localNote: "The district clerk in the county of the decree mails the judgment." },
  }),
  office({
    code: "UT",
    name: "Utah",
    office: "Utah Office of Vital Records and Statistics",
    mail: "Utah Department of Health and Human Services\nOffice of Vital Records and Statistics\nP.O. Box 141012\nSalt Lake City, UT 84114-1012",
    phone: "(801) 538-6105",
    url: "https://vitalrecords.utah.gov/",
    birth: { since: "1905" },
    marriage: { holder: "both", since: "1978 at the state office", localNote: "County clerks mail marriage licenses for every year. The state office has records from 1978." },
  }),
  office({
    code: "VT",
    name: "Vermont",
    office: "Vermont Department of Health\nVital Records",
    mail: "Vermont Department of Vital Records\n280 State Drive\nWaterbury, VT 05671-8370",
    phone: "(802) 863-7275",
    url: "https://www.healthvermont.gov/stats/vital-records",
    inPerson: "280 State Drive, Waterbury, VT 05671",
    birth: { since: "1909 in the statewide registry", localNote: "Records before 1909 are at the town clerk where the event happened. Town clerks can also help with later records." },
    marriage: { holder: "both", since: "1909", localNote: "For a marriage before 1909, mail the town clerk. Town clerk contacts are listed by the Vermont Secretary of State." },
  }),
  office({
    code: "VA",
    name: "Virginia",
    office: "Virginia Office of Vital Records",
    mail: "Office of Vital Records\nP.O. Box 1000\nRichmond, VA 23218-1000",
    phone: "(804) 662-6200",
    url: "https://www.vdh.virginia.gov/vital-records/",
    birth: { since: "January 1853–December 1896 and since June 14, 1912", localNote: "For the gap between 1896 and June 14, 1912, mail the health department in the city where the event happened." },
    marriage: { holder: "both", since: "January 1853", localNote: "The circuit court clerk in the county or city of the license can mail a copy." },
  }),
  office({
    code: "WA",
    name: "Washington",
    office: "Washington State Department of Health\nCenter for Health Statistics",
    mail: "Washington State Department of Health\nCenter for Health Statistics\nP.O. Box 9709\nOlympia, WA 98507-9709",
    phone: "(360) 236-4300",
    url: "https://doh.wa.gov/licenses-permits-and-certificates/vital-records",
    birth: { since: "July 1907", localNote: "Events before July 1907 are at the county auditor. County auditors can also mail many later certificates." },
    marriage: { holder: "both", since: "January 1968 at the state office", localNote: "The county auditor where the license was issued can mail a copy for any year." },
  }),
  office({
    code: "WV",
    name: "West Virginia",
    office: "West Virginia Vital Registration",
    mail: "Vital Registration Office\n350 Capitol Street, Room 165\nCharleston, WV 25301-3701",
    phone: "(304) 558-2931",
    url: "https://dhhr.wv.gov/bph/pages/vital-records.aspx",
    inPerson: "350 Capitol Street, Room 165, Charleston, WV 25301",
    birth: { since: "January 1917", localNote: "Earlier records are at the county clerk where the event happened." },
    marriage: { holder: "both", since: "January 1964", localNote: "Licenses before January 1964 are at the county clerk. That clerk can also mail later licenses." },
  }),
  office({
    code: "WI",
    name: "Wisconsin",
    office: "Wisconsin Vital Records",
    mail: "Wisconsin Vital Records\nP.O. Box 309\nMadison, WI 53701-0309",
    phone: "(608) 266-1373",
    url: "https://www.dhs.wisconsin.gov/vitalrecords/index.htm",
    birth: { since: "Some records from 1814; early years are incomplete", localNote: "Register of deeds offices in the county of the event can mail certified copies and are often the faster path when the state site rejects a former name." },
    marriage: { holder: "both", since: "April 1835", localNote: "The register of deeds in the county of the license can mail a copy." },
  }),
  office({
    code: "WY",
    name: "Wyoming",
    office: "Wyoming Vital Statistics Services",
    mail: "Vital Statistics Services\n2300 Capitol Avenue\nCheyenne, WY 82002",
    phone: "(307) 777-7591",
    url: "https://health.wyo.gov/admin/vitalstatistics/",
    inPerson: "2300 Capitol Avenue, Cheyenne, WY 82002",
    birth: { since: "July 1909" },
    marriage: { holder: "both", since: "May 1941", localNote: "The county clerk where the license was issued can mail a copy, including licenses before May 1941." },
  }),
];

const byCode = new Map(JURISDICTIONS.map((item) => [item.code, item]));

export function listJurisdictions() {
  return JURISDICTIONS.map((item) => ({
    code: item.code,
    name: item.name,
    phone: item.vital.phone,
    url: item.vital.url,
    countyCount: item.counties.length,
    records: Object.fromEntries(
      Object.entries(item.records).map(([key, spec]) => [key, { holder: spec.holder, portal: spec.portal, since: spec.since }])
    ),
  }));
}

export function getJurisdiction(code) {
  if (!code) return null;
  return byCode.get(String(code).toUpperCase()) || null;
}

export const RECORD_TYPES = [
  { id: "birth", title: "Birth certificate", blurb: "Certified long-form copy, including a certificate filed under a former name." },
  { id: "death", title: "Death certificate", blurb: "Certified copy from the state office or the local registrar." },
  { id: "marriage", title: "Marriage certificate", blurb: "The license is often at the county clerk, even when the state has no online order." },
  { id: "divorce", title: "Divorce record", blurb: "Usually a court clerk. The letter asks that court to mail the decree." },
  { id: "adoption", title: "Adoption or sealed birth record", blurb: "Gets the certificate in your current name, and the legal next step if the original record is sealed." },
  { id: "driver", title: "My driver record", blurb: "A request for your own motor-vehicle record. The state still checks your identity." },
];
